reviews:
  pre_merge_checks:
    custom_checks:
      - name: "Error Handling"
        mode: "error"
        instructions: "Ensure methods handle invalid inputs or possible errors. Methods should validate inputs or use proper error handling mechanisms."

      - name: "Naming Conventions"
        mode: "error"
        instructions: "Class names and method names must follow C# PascalCase naming conventions. Avoid snake_case, camelCase, or inconsistent capitalization."

      - name: "Code Comments"
        mode: "warning"
        instructions: "Public methods should include a short comment describing their purpose. Comments must be clear, meaningful, and helpful."

      - name: "Console Logging"
        mode: "warning"
        instructions: "Console output must be meaningful and clearly describe what is being printed. Avoid vague or unclear Console.WriteLine messages."

      - name: "Clean & Readable Code"
        mode: "warning"
        instructions: "Code must be clean, readable, well-structured, and follow proper indentation, spacing, and formatting."

  path_instructions:
    - path: "**/*.cs"
      instructions: |
        Review all C# source code and ensure the following:

        - Methods must handle invalid inputs or possible errors. Ensure inputs are validated or wrapped
          in try-catch blocks when needed. Avoid assuming inputs are always valid.
        - Class names and method names must follow C# PascalCase naming conventions. Avoid using
          snake_case, camelCase, or inconsistent capitalization.
        - Public methods should include a short, clear comment describing their purpose. Comments must
          be meaningful, accurate, and helpful for other developers.
        - Console.WriteLine output must clearly describe what is being printed. Avoid vague or
          meaningless messages such as “Done” or “OK”.
        - Code must be clean, readable, and well-structured. Ensure consistent indentation, spacing,
          and formatting across all files. Avoid unnecessary complexity or clutter.
